# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6e39ea02dcd02b4d0cf5630891157170114bf9678db82be2c8b95b9fba96efe20ddaa344c5bbe9675b4a522c7363528510272225fa5d8834fa84b1bea35ded

test:
  secret_key_base: 0b701b3d5063a298bf329634935cb273bb468f99315a4f7b5f814feb8cd602678d46482e94f24d2898cb3305f06b17c4fa824377446bd875410655268c22371e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
